;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================
;AURORA BOREALIS themed Polybar configuration

[colors]
transparent = #00
white = #FFFFFF
black = #000000

color0 = #D9303E
color1 = #1E2626
color2 = #81A6A6
color3 = #B4D2D9
color4 = #455959

background = ${colors.color1}
highlight = ${colors.color2}
special = ${colors.color0}
bright = ${colors.color3}
fade = ${colors.color4}

[bar/main]
width = 98.8%
offset-x = 0.7%
offset-y = 1%
height = 24pt
radius = 10
bottom = true
fixed-center = false

; dpi = 96

; bar colors
background = ${colors.background}
foreground = ${colors.white}
border-color = ${colors.special}

line-size = 0
border-top-size = 0

padding-left = 3
padding-right = 3

module-margin = 1

separator = |
separator-foreground = ${colors.background}
separator-padding = 0

font-0 = Noto Sans:style=Regular:size=10.5;2
font-1 = Symbols Nerd Font Mono:style=Regular:size=10;2

modules-left = xworkspaces show-desk skippy-xd zzzfm-preferences control-center file-manager trash-bin neovim mongodb-compass postman google-chrome youtube icewm-manager
modules-center = active-window
modules-right = unplug-drive filesystem memory cpu pulseaudio popup-calendar time power-menu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

icon-default = ""

label-active = ""
label-active-background = ${colors.background}
label-active-foreground = ${colors.bright}
label-active-underline= ${colors.background}
label-active-padding = 1

label-occupied = ""
label-occupied-foreground = ${colors.bright}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.special}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.bright}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
format = <label>
label = %class:0:60:...%
; label-maxlen = 15 
label-empty = 

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#81A6A6} %mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.fade}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰌡  "
format-volume-prefix-foreground = ${colors.highlight}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = " 󰖁  "
label-muted-foreground = ${colors.fade}

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 2

; Right and Middle click
click-right = pavucontrol
; click-middle = 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.highlight}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.transparent}
label-indicator-background = ${colors.white}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.highlight}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.highlight}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/time]
type = internal/date
interval = 1

; date = %a, %d %h
; date-alt = %d %B %Y 
time = %l:%M %p
time-alt = %l:%M:%S %p

format-prefix = " "
label = %time%
label-background= ${colors.background}
format-prefix-foreground = ${colors.highlight}

[module/popup-calendar]
format-prefix = "|    󰸗 "
format-prefix-foreground = ${colors.highlight}
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/system-usb-udev]
type = custom/script
exec = ~/.config/polybar/scripts/system-usb-udev.sh
tail = true
click-left = ~/.config/polybar/scripts/system-usb-udev.sh --mount &
click-right = ~/.config/polybar/scripts/system-usb-udev.sh --unmount &

[module/power-menu]
type = custom/script
exec = echo "⏻"
format = <label>
label-foreground = ${colors.special}
click-left = /usr/local/bin/desktop-session-exit

; [module/temp]
; type = internal/temperature
; interval = 3
; thermal-zone = 0
; hwmon-path = /sys/class/hwmon/hwmon1/temp1_input
; base-temperature = 36 
; warn-temperature = 60
; units = true

; format =<label>
; format-prefix = " "
; format-prefix-foreground= ${colors.primary}

; label = %temperature-c%
; label-foreground = ${colors.white}
; label-padding-left=2
; label-padding-right=2

; format-warn-prefix = " "
; format-warn-prefix-foreground= ${colors.red}

; label-warn = %temperature-c%
; label-warn-foreground = ${colors.red}
; label-warn-padding-left=2
; label-warn-padding-right=2

[module/active-window]
type = custom/script
format-background = ${colors.background}
format-foreground = ${colors.white}
format-padding = 1
exec = ~/.config/polybar/scripts/active-window.sh
interval = 1

[module/zzzfm-preferences]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = zzzfm --desktop-pref

[module/show-desk]
type = custom/script
exec = echo "|     "
format = <label>
label-foreground = ${colors.highlight}
# label-padding-left = 5
click-left = xdotool key ctrl+alt+d

[module/skippy-xd]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = skippy-xd

[module/unplug-drive]
type = custom/script
exec = echo "󰕓"
format = <label>
label-foreground = ${colors.highlight}
click-left = unplugdrive.sh

[module/file-manager]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = desktop-defaults-run -fm

[module/icewm-manager]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /usr/local/bin/icewm-manager-gui

[module/trash-bin]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = zzzfm ~/.local/share/Trash/files/

[module/youtube]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /opt/google/chrome/google-chrome --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml

[module/control-center]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = antixcc.sh

[module/google-chrome]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /usr/bin/google-chrome-stable

[module/mongodb-compass]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /usr/bin/mongodb-compass

[module/postman]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = ~/Postman/app/postman

[module/neovim]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = ~/.config/polybar/scripts/run_nvim.sh

; vim:ft=dosini
